steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/wns:$SHORT_SHA", "./"]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/wns:$SHORT_SHA"]
  # deploy container image to GKE
# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=kubernetes-resource-file
#   - --image=gcr.io/project-id/image:tag
#   - --location=location
#   - --cluster=cluster
