steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/wns:$SHORT_SHA", "./testapp"]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/wns:$SHORT_SHA"]
  # deploy container image to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - $_CONTAINER_NAME=gcr.io/$PROJECT_ID/$_IMAGE_PATH:$SHORT_SHA  
  
  
  

