apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angularapp
  template:
    metadata:
      labels:
        app: angularapp
    spec:
      containers:
      - name: wns-sha256-1
        image: gcr.io/playground-s-11-799c3f06/wns:sha256:1ed1e17ccabb09038cfb8a965337ebcda51ef9e9d32082164c502d44d9731a02
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: angularapp-service
spec:
  type: LoadBalancer
  selector:
    app: angularapp
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
